definitions:
  models.CreateDocumentRequest:
    properties:
      content:
        type: string
      title:
        type: string
    type: object
  models.CreateDocumentResponse:
    properties:
      uuid:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: A collaborative text editor.
  title: GoPad Swagger API
  version: "1.0"
paths:
  /documents:
    post:
      consumes:
      - application/json
      description: takes title and content and create a new document
      parameters:
      - description: title
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.CreateDocumentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: JSON Content
          schema:
            $ref: '#/definitions/models.CreateDocumentResponse'
      summary: Create a new document
      tags:
      - document
swagger: "2.0"
